# Generated by Django 4.0 on 2021-12-29 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.category'),
            preserve_default=False,
        ),
    ]
