# Generated by Django 4.0 on 2022-01-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(default='', upload_to='Home/'),
            preserve_default=False,
        ),
    ]
