# Generated by Django 4.0 on 2022-01-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_home_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
