# Generated by Django 4.0 on 2022-01-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_home_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
